language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - sudo apt-get update
  - sudo apt-get install libsdl2-dev libsdl2-gfx-dev
  - sudo apt-get install  binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
after_success: |
    [ $TRAVIS_RUST_VERSION = stable ] &&
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && cd ../.. &&
    ls target/debug &&
    ./kcov-master/tmp/usr/local/bin/kcov –coveralls-id=$TRAVIS_JOB_ID –exclude-pattern=/.cargo target/kcov target/debug/chip8vm
